slack:
  api:
    key: xoxb-YOUR-KEY
  channel: channelname
logging:
  level:
    com.recursivechaos: DEBUG

jobdetail:
  standup:
    greeting: "Hello world!"
    time: "0 25 9 ? * MON,TUE,WED,THU *"
